export const UniversitiesContent = {
  title: "Convenios Universitarios",
  universities: [
    // --- Lista inicial ---
    { id: "abat-oliba", name: "Universitat Abat Oliba CEU" },
    { id: "alcala", name: "Universidad de Alcalá" },
    { id: "almeria", name: "Universidad de Almería" },
    { id: "autonoma-barcelona", name: "Universitat Autònoma de Barcelona" },
    { id: "barcelona", name: "Universitat de Barcelona" },
    { id: "cadiz", name: "Universidad de Cádiz" },
    { id: "cantabria", name: "Universidad de Cantabria" },
    { id: "carlos-iii", name: "Universidad Carlos III de Madrid" },
    { id: "catolica-avila", name: "Universidad Católica de Ávila" },
    { id: "catolica-valencia", name: "Universitat Católica de València Sant Vicent Màrtir" },
    { id: "cordoba", name: "Universidad de Córdoba" },
    { id: "deusto", name: "Universidad de Deusto" },
    { id: "miguel-cervantes", name: "Universidad Europea Miguel de Cervantes" },
    { id: "girona", name: "Universitat de Girona" },
    { id: "huelva", name: "Universidad de Huelva" },
    { id: "andalucia", name: "Universidad Internacional de Andalucía" },
    { id: "menendez-pelayo", name: "Universidad Internacional Menéndez Pelayo" },
    { id: "jaume-i", name: "Universitat Jaume I" },
    { id: "rioja", name: "Universidad de La Rioja" },
    { id: "leon", name: "Universidad de León" },
    { id: "malaga", name: "Universidad de Málaga" },
    { id: "mondragon", name: "Mondragón Unibertsitatea" },
    { id: "valladolid", name: "Universidad de Valladolid" },
    { id: "vigo", name: "Universidad de Vigo" },

    // --- Nuevas de la imagen ---
    { id: "pontificia-salamanca", name: "Universidad Pontificia de Salamanca" },
    { id: "ramon-llull", name: "Universitat Ramón Llull" },
    { id: "oviedo", name: "Universidad de Oviedo" },
    { id: "rovira-virgili", name: "Universitat Rovira i Virgili" },
    { id: "salamanca", name: "Universidad de Salamanca" },
    { id: "san-pablo-ceu", name: "Universidad San Pablo-CEU" },
    { id: "sevilla", name: "Universidad de Sevilla" },
    { id: "valencia", name: "Universitat de València" },
    { id: "vic", name: "Universitat de Vic" },
    { id: "zaragoza", name: "Universidad de Zaragoza" },
    { id: "alacant", name: "Universitat d'Alacant" },
    { id: "alfonso-x-sabio", name: "Universidad Alfonso X El Sabio" },
    { id: "nebrija", name: "Universidad Antonio de Nebrija" },
    { id: "autonoma-madrid", name: "Universidad Autónoma de Madrid" },
    { id: "burgos", name: "Universidad de Burgos" },
    { id: "camilo-jose-cela", name: "Universidad Camilo José Cela" },
    { id: "cardenal-herrera", name: "Universidad Cardenal Herrera-CEU" },
    { id: "castilla-la-mancha", name: "Universidad de Castilla-La Mancha" },
    { id: "san-antonio-murcia", name: "Universidad Católica San Antonio de Murcia" },
    { id: "complutense", name: "Universidad Complutense de Madrid" },
    { id: "coruna", name: "Universidade da Coruña" },
    { id: "europea-madrid", name: "Universidad Europea de Madrid" },
    { id: "pais-vasco", name: "Euskal Herriko Unibertsitatea / Universidad del País Vasco" },
    { id: "santiago-compostela", name: "Universidade de Santiago de Compostela" },
    { id: "uned", name: "U.N.E.D." },
    { id: "francisco-vitoria", name: "Universidad Francisco de Vitoria" },
    { id: "granada", name: "Universidad de Granada" },
    { id: "navarra", name: "Universidad de Navarra" },
    { id: "politecnica-cartagena", name: "Universidad Politécnica de Cartagena" },
    { id: "politecnica-madrid", name: "Universidad Politécnica de Madrid" },
    { id: "pompeu-fabra", name: "Universitat Pompeu Fabra" },
    { id: "illes-balears", name: "Universitat de les Illes Balears" },
    { id: "internacional-catalunya", name: "Universitat Internacional de Catalunya" },
    { id: "jaen", name: "Universidad de Jaén" },
    { id: "la-laguna", name: "Universidad de La Laguna" },
    { id: "las-palmas", name: "Universidad de Las Palmas de Gran Canaria" },
    { id: "lleida", name: "Universitat de Lleida" },
    { id: "miguel-hernandez", name: "Universitat Miguel Hernández d'Elx" },
    { id: "murcia", name: "Universidad de Murcia" },
    { id: "oberta-catalunya", name: "Universitat Oberta de Catalunya" },
    { id: "pablo-olavide", name: "Universidad Pablo de Olavide" },
    { id: "politecnica-catalunya", name: "Universitat Politècnica de Catalunya" },
    { id: "politecnica-valencia", name: "Universitat Politècnica de València" },
    { id: "pontificia-comillas", name: "Universidad Pontificia Comillas" },
    { id: "publica-navarra", name: "Universidad Pública de Navarra" },
    { id: "rey-juan-carlos", name: "Universidad Rey Juan Carlos" },
    { id: "sek", name: "Universidad S.E.K." },
    { id: "san-jorge", name: "Universidad San Jorge" },
  ],
};