

export const UniversitiesContent = {
  title: "Convenios Universitarios",
  universities: [
    // --- Lista inicial ---
    { id: "abat-oliba", name: "Universitat Abat Oliba CEU", url: "https://www.uaoceu.es/" },
    { id: "alcala", name: "Universidad de Alcalá", url: "https://www.uah.es/" },
    { id: "almeria", name: "Universidad de Almería", url:"https://www.ual.es/" },
    { id: "autonoma-barcelona", name: "Universitat Autònoma de Barcelona", url:"https://www.uab.cat/" },
    { id: "barcelona", name: "Universitat de Barcelona", url:"https://web.ub.edu/web/ub/"},
    { id: "cadiz", name: "Universidad de Cádiz" , url:"https://www.uca.es/"},
    { id: "cantabria", name: "Universidad de Cantabria", url:"https://www.unican.es/"},
    { id: "carlos-iii", name: "Universidad Carlos III de Madrid",url:"https://www.uc3m.es/"},
    { id: "catolica-avila", name: "Universidad Católica de Ávila" , url:"https://www.ucavila.es/?lang=es"},
    { id: "catolica-valencia", name: "Universitat Católica de València Sant Vicent Màrtir", url:"https://www.ucv.es/"},
    { id: "cordoba", name: "Universidad de Córdoba", url:"https://www.uco.es/"},
    { id: "deusto", name: "Universidad de Deusto" , url:"https://www.deusto.es/es/inicio"},
    { id: "miguel-cervantes", name: "Universidad Europea Miguel de Cervantes", url:"https://www.uemc.es/"},
    { id: "girona", name: "Universitat de Girona", url:"https://www.udg.edu/ca/"},
    { id: "huelva", name: "Universidad de Huelva", url:"https://www.uhu.es/"},
    { id: "andalucia", name: "Universidad Internacional de Andalucía", url:"http://www.unia.es/"},
    { id: "menendez-pelayo", name: "Universidad Internacional Menéndez Pelayo", url:"https://www.uimp.es/" },
    { id: "jaume-i", name: "Universitat Jaume I", url :"https://www.uji.es/"},
    { id: "rioja", name: "Universidad de La Rioja", url:"https://www.unirioja.es/"},
    { id: "leon", name: "Universidad de León", url:"https://www.unileon.es/"},
    { id: "malaga", name: "Universidad de Málaga", url:"https://www.uma.es/"},
    { id: "mondragon", name: "Mondragón Unibertsitatea", url:"http://www.mondragon.edu/es"},
    { id: "valladolid", name: "Universidad de Valladolid",url:"http://www.uji.eshttp//www.uva.es/portal/paginas/portada" },
    { id: "vigo", name: "Universidad de Vigo", url:"https://www.uvigo.gal/" },

    // --- Nuevas de la imagen ---
    { id: "pontificia-salamanca", name: "Universidad Pontificia de Salamanca", url:"https://www.upsa.es/"},
    { id: "ramon-llull", name: "Universitat Ramón Llull", url:"https://www.url.edu/ca"},
    { id: "oviedo", name: "Universidad de Oviedo", url:"https://www.uniovi.es/inicio/" },
    { id: "rovira-virgili", name: "Universitat Rovira i Virgili", url:"https://www.urv.cat/ca/" },
    { id: "salamanca", name: "Universidad de Salamanca", url:"https://usal.es/" },
    { id: "san-pablo-ceu", name: "Universidad San Pablo-CEU", url:"https://www.uspceu.com/" },
    { id: "sevilla", name: "Universidad de Sevilla", url:"https://www.us.es/" },
    { id: "valencia", name: "Universitat de València", url:"https://www.uv.es/" },
    { id: "vic", name: "Universitat de Vic", url:"https://www.uvic.es/"},
    { id: "zaragoza", name: "Universidad de Zaragoza", url:"https://www.unizar.es/" },
    { id: "alacant", name: "Universitat d'Alacant", url:"https://www.ua.es/" },
    { id: "alfonso-x-sabio", name: "Universidad Alfonso X El Sabio", url:"https://www.uax.com/" },
    { id: "nebrija", name: "Universidad Antonio de Nebrija", url:"https://www.nebrija.com/" },
    { id: "autonoma-madrid", name: "Universidad Autónoma de Madrid", url :"https://www.uam.es/ss/Satellite/es/home/" },
    { id: "burgos", name: "Universidad de Burgos", url:"https://www.ubu.es/" },
    { id: "camilo-jose-cela", name: "Universidad Camilo José Cela", url:"https://www.ucjc.edu/" },
    { id: "cardenal-herrera", name: "Universidad Cardenal Herrera-CEU", url:"http://www.uch.ceu.es/" },
    { id: "castilla-la-mancha", name: "Universidad de Castilla-La Mancha", url:"https://www.uclm.es/" },
    { id: "san-antonio-murcia", name: "Universidad Católica San Antonio de Murcia", url:"https://www.ucam.edu/" },
    { id: "complutense", name: "Universidad Complutense de Madrid", url:"https://www.ucm.es/" },
    { id: "coruna", name: "Universidade da Coruña", url:"https://www.udc.gal/" },
    { id: "europea-madrid", name: "Universidad Europea de Madrid", url:"https://universidadeuropea.com/"},
    { id: "pais-vasco", name: "Euskal Herriko Unibertsitatea / Universidad del País Vasco", url:"https://www.ehu.eus/es/" },
    { id: "santiago-compostela", name: "Universidade de Santiago de Compostela", url:"https://www.usc.gal/gl"},
    { id: "uned", name: "U.N.E.D.", url:"https://www.uned.es/universidad/inicio.html" },
    { id: "francisco-vitoria", name: "Universidad Francisco de Vitoria", url:"https://www.ufv.es/" },
    { id: "granada", name: "Universidad de Granada", url:"https://www.ugr.es/" },
    { id: "navarra", name: "Universidad de Navarra", url:"https://www.unav.edu/" },
    { id: "politecnica-cartagena", name: "Universidad Politécnica de Cartagena", url:"https://www.upct.es/" },
    { id: "politecnica-madrid", name: "Universidad Politécnica de Madrid", url:"https://www.upm.es/" },
    { id: "pompeu-fabra", name: "Universitat Pompeu Fabra", url:"https://www.upf.edu/" },
    { id: "illes-balears", name: "Universitat de les Illes Balears", url:"https://www.uib.es/inici" },
    { id: "internacional-catalunya", name: "Universitat Internacional de Catalunya", url:"http://www.unica.edu/" },
    { id: "jaen", name: "Universidad de Jaén", url:"https://www10.ujaen.es/" },
    { id: "la-laguna", name: "Universidad de La Laguna", url:"https://www.ull.es/" },
    { id: "las-palmas", name: "Universidad de Las Palmas de Gran Canaria", url:"https://www10.ulpgc.es/" },
    { id: "lleida", name: "Universitat de Lleida", url:"https://www.udl.cat/ca/" },
    { id: "miguel-hernandez", name: "Universitat Miguel Hernández d'Elx", url:"https://www.umh.es/"},
    { id: "murcia", name: "Universidad de Murcia", url:"https://www.uoc.edu/es" },
    { id: "oberta-catalunya", name: "Universitat Oberta de Catalunya", url:"https://www.uoc.edu/es" },
    { id: "pablo-olavide", name: "Universidad Pablo de Olavide", url:"https://www.upo.es/portal/impe/web/portada/index.html" },
    { id: "politecnica-catalunya", name: "Universitat Politècnica de Catalunya", url:"https://www.upc.edu/ca" },
    { id: "politecnica-valencia", name: "Universitat Politècnica de València", url:"https://www.upv.es/" },
    { id: "pontificia-comillas", name: "Universidad Pontificia Comillas" },
    { id: "publica-navarra", name: "Universidad Pública de Navarra", url:"https://www.unavarra.es/portada" },
    { id: "rey-juan-carlos", name: "Universidad Rey Juan Carlos,", url:"https://www.urjc.es/" },
    { id: "sek", name: "Universidad S.E.K.", url:"http://www.usek.es/"},
    { id: "san-jorge", name: "Universidad San Jorge", url:"https://www.usj.es/" },
  ],
};